import { z } from 'zod';

// --- Medications ---
export const MedicationSchema = z.object({
    id: z.string().uuid().optional(),
    name: z.string().min(1, "Le nom du médicament est requis"),
    dosage: z.string().min(1, "Le dosage est requis"),
    frequency: z.string().min(1, "La fréquence est requise"),
    duration: z.string().min(1, "La durée est requise"),
    instructions: z.string().optional(),
});

export type Medication = z.infer<typeof MedicationSchema>;

// --- Prescriptions ---
export const PrescriptionStatusSchema = z.enum(['active', 'dispensed', 'expired']);
export type PrescriptionStatus = z.infer<typeof PrescriptionStatusSchema>;

export const PrescriptionSchema = z.object({
    id: z.string().uuid().optional(),
    prescriptionNumber: z.string().optional(), // Generated by backend (e.g. ORD-2025-00001)
    patientId: z.string().min(1, "L'ID du patient est requis"),
    doctorId: z.string().min(1, "L'ID du médecin est requis"),
    status: PrescriptionStatusSchema.default('active'),
    notes: z.string().optional(),
    validUntil: z.coerce.date(), // Use coerce to handle string dates from JSON
    medications: z.array(MedicationSchema).min(1, "Au moins un médicament est requis"),
    createdAt: z.coerce.date().optional(),
    updatedAt: z.coerce.date().optional(),
});

export type Prescription = z.infer<typeof PrescriptionSchema>;

// --- Teleconsultations ---
export const TeleconsultStatusSchema = z.enum(['scheduled', 'in-progress', 'completed', 'cancelled']);
export type TeleconsultStatus = z.infer<typeof TeleconsultStatusSchema>;

export const TeleconsultSessionSchema = z.object({
    id: z.string().uuid().optional(),
    sessionNumber: z.string().optional(), // Generated by backend (e.g. TC-2025-00001)
    patientId: z.string().min(1, "L'ID du patient est requis"),
    doctorId: z.string().min(1, "L'ID du médecin est requis"),
    scheduledAt: z.coerce.date(),
    durationMinutes: z.number().int().positive().default(30),
    status: TeleconsultStatusSchema.default('scheduled'),
    dailyRoomUrl: z.string().url().optional(),
    dailyRoomName: z.string().optional(),
    notes: z.string().optional(),
    createdAt: z.coerce.date().optional(),
    updatedAt: z.coerce.date().optional(),
});

export type TeleconsultSession = z.infer<typeof TeleconsultSessionSchema>;

// --- Audit Logs ---
export const AuditActionSchema = z.enum(['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'EXPORT']);
export type AuditAction = z.infer<typeof AuditActionSchema>;

export const AuditResourceSchema = z.enum(['PRESCRIPTION', 'TELECONSULT', 'PATIENT']);
export type AuditResource = z.infer<typeof AuditResourceSchema>;

export const AuditLogSchema = z.object({
    id: z.string().uuid().optional(),
    userId: z.string().min(1),
    action: AuditActionSchema,
    resourceType: AuditResourceSchema,
    resourceId: z.string().min(1),
    details: z.record(z.any()).optional(),
    ipAddress: z.string().optional(),
    createdAt: z.coerce.date().optional(),
});

export type AuditLog = z.infer<typeof AuditLogSchema>;
